print("Calculator Program")
first_number = input("first number")
second_number = input("second number")
third_number = input("third number")
print(int(first_number) + int(second_number) + int(third_number))